# Generated by Django 2.2.24 on 2021-12-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField(default='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('qualis', models.TextField(default='')),
                ('area', models.TextField(default='')),
                ('local', models.TextField(default='')),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='horarios_laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.TextField(default='')),
                ('hora_entrada', models.DateTimeField(default='')),
                ('hora_saida', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField()),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('funcao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemaEnfrentado', models.TextField()),
                ('comentarioProblema', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='situacaoAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.TextField(default='...')),
            ],
        ),
        migrations.CreateModel(
            name='StatusArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico_Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('dataNascimento', models.TextField(default='01/01/0000')),
                ('endereco', models.TextField(default='...')),
                ('telefone', models.TextField(default='3333-3333')),
                ('cpf', models.TextField(default='12345678901', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('titulo', models.TextField()),
                ('corpo', models.TextField()),
                ('data_lancamento_noticia', models.DateTimeField(null=True)),
                ('imagem', models.ImageField(upload_to='media')),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.TextField(null=True, unique=True)),
                ('email', models.TextField()),
                ('telefone', models.TextField()),
                ('data_nascimento', models.DateField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.TextField()),
                ('hora_inicio', models.DateTimeField(null=True)),
                ('hora_fim', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tecnico_resposavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Tecnico_Campo')),
            ],
        ),
        migrations.CreateModel(
            name='atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.TextField(default='999999999999')),
                ('endereco', models.TextField(default='...')),
                ('atendimentosRelacionados', models.ManyToManyField(to='sistemaReclamacoes.atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('coautor', models.TextField(default='')),
                ('orientador', models.TextField(default='')),
                ('autor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Professor')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.StatusArtigo')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField(default='')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('data_nascimento', models.TextField(max_length=20)),
                ('eventos_cadastrado', models.ManyToManyField(to='sistemaReclamacoes.Evento')),
            ],
        ),
    ]
